# theme: jekyll-theme-modernist
name: Promoting Your Novel 
markdown: kramdown

gems:
  - jekyll-sitemap                  # Generate sitemaps automatically
  - jekyll-feed                     # Generate RSS feed automatically
