# DON'T USE TAB CHARACTERS TO INDENT

name: Promoting Your Novel 
markdown: kramdown

# Location of generated site. Basis for links in the RSS feed.
url: http://www.promotingyournovel.com/

baseurl: "/promotingyournovel"

# Probably not necessary with recent GitHub Pages version?
permalink: pretty

gems:
  - jekyll-sitemap                  # Generate sitemaps automatically
  - jekyll-feed                     # Generate RSS feed automatically
